import {
  CitizenRequest,
  Hotspot,
  AIRecommendation,
  InfrastructureAsset,
  DataSourceItem,
  User,
  Project,
} from '../../../../packages/shared/src/types';

export const SEED_USERS: (User & { passwordHash: string })[] = [
  {
    id: 'usr-citizen-1',
    name: 'Ramesh Patel',
    phone: '+919876543210',
    email: 'ramesh.patel@example.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a', // password123
    role: 'CITIZEN',
    preferredLanguage: 'hi',
    district: 'Barmer',
    state: 'Rajasthan',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'usr-citizen-2',
    name: 'Ananya Roy',
    phone: '+919876543211',
    email: 'ananya.roy@example.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'CITIZEN',
    preferredLanguage: 'bn',
    district: 'Purulia',
    state: 'West Bengal',
    createdAt: '2026-08-12T11:00:00Z',
  },
  {
    id: 'usr-officer-district',
    officerId: 'district.demo',
    name: 'Dr. Vikramaditya Rathore, IAS',
    phone: '+919876543220',
    email: 'dm.barmer@raj.gov.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'DISTRICT_OFFICER',
    preferredLanguage: 'hi',
    district: 'Barmer',
    state: 'Rajasthan',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'usr-officer-state',
    officerId: 'state.demo',
    name: 'Sunita Meena, IAS',
    phone: '+919876543221',
    email: 'sec.infra@raj.gov.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'STATE_OFFICER',
    preferredLanguage: 'hi',
    district: 'Jaipur',
    state: 'Rajasthan',
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'usr-officer-national',
    officerId: 'national.demo',
    name: 'Arun K. Sharma, IAS',
    phone: '+919876543222',
    email: 'director.infrastructure@gov.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'NATIONAL_OFFICER',
    preferredLanguage: 'en',
    district: 'New Delhi',
    state: 'Delhi',
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'usr-analyst',
    officerId: 'analyst.demo',
    name: 'Pooja Iyer',
    phone: '+919876543223',
    email: 'analyst.niti@gov.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'ANALYST',
    preferredLanguage: 'en',
    district: 'New Delhi',
    state: 'Delhi',
    createdAt: '2026-05-20T08:00:00Z',
  },
  {
    id: 'usr-admin',
    officerId: 'admin.demo',
    name: 'System Administrator',
    phone: '+919876543299',
    email: 'admin@jansetu.gov.in',
    passwordHash: '$2a$10$wTqgU9zK.x5yUf9v/9gQaeDk3cT3K9b.o2E0r7gW5b3lJ5kQ3hY1a',
    role: 'ADMIN',
    preferredLanguage: 'en',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const SEED_REQUESTS: CitizenRequest[] = [
  {
    id: 'REQ-2026-0081',
    citizenId: 'usr-citizen-1',
    citizenName: 'Ramesh Patel',
    citizenPhone: '+919876543210',
    title: 'Severe road deterioration halting monsoon emergency ambulance access',
    description:
      'The 6km link road connecting Chohtan tehsil to Shivnagar village has completely washed away, leaving 14,000 residents without all-weather ambulance access.',
    originalText: 'हमारे गांव में सड़क बहुत खराब है और बारिश के समय एम्बुलेंस नहीं आ पाती। पिछले हफ्ते एक गर्भवती महिला को खाट पर ले जाना पड़ा।',
    translatedText:
      'The road in our village is in very bad condition and ambulances cannot reach during the rainy season. Last week a pregnant woman had to be carried on a cot.',
    language: 'hi',
    category: 'ROAD',
    subcategory: 'Rural Arterial Disconnection',
    urgency: 'HIGH',
    status: 'UNDER_REVIEW',
    latitude: 25.7521,
    longitude: 71.3967,
    state: 'Rajasthan',
    district: 'Barmer',
    block: 'Chohtan',
    village: 'Shivnagar',
    aiConfidence: 0.94,
    createdAt: '2026-09-24T08:14:00Z',
    updatedAt: '2026-09-24T10:30:00Z',
    similarCount: 28,
    media: [
      {
        id: 'med-1',
        requestId: 'REQ-2026-0081',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
        mimeType: 'image/jpeg',
        createdAt: '2026-09-24T08:14:00Z',
      },
    ],
    analysis: {
      id: 'ana-1',
      requestId: 'REQ-2026-0081',
      detectedProblem: 'Pothole density >4.2/100m, washed unpaved road embankment impeding 108 emergency vehicle transit',
      primaryCategory: 'ROAD',
      secondaryCategory: 'HEALTHCARE',
      urgencyReason: 'Direct disruption of maternal and emergency healthcare response during active rains',
      affectedPopulationEstimate: 14200,
      duplicateGroupId: 'DUP-BARMER-ROAD-01',
      aiConfidence: 0.94,
      reasoningSummary:
        'Multimodal vision analysis confirmed acute sub-base erosion and rutting. Geocoding correlates with high infant mortality risk zone and 18-kilometer detour to nearest CHC.',
      createdAt: '2026-09-24T08:15:00Z',
    },
    statusHistory: [
      {
        id: 'hist-1',
        requestId: 'REQ-2026-0081',
        status: 'SUBMITTED',
        comment: 'Received through JanSetu Citizen Voice Input in Hindi.',
        updatedBy: 'JanSetu Voice Pipeline',
        createdAt: '2026-09-24T08:14:00Z',
      },
      {
        id: 'hist-2',
        requestId: 'REQ-2026-0081',
        status: 'AI_VERIFIED',
        comment: 'AI verified road connectivity crisis with emergency health risk. Clustered with 27 nearby reports.',
        updatedBy: 'JanSetu AI Engine v3.8',
        createdAt: '2026-09-24T08:15:00Z',
      },
      {
        id: 'hist-3',
        requestId: 'REQ-2026-0081',
        status: 'UNDER_REVIEW',
        comment: 'Acknowledged by Barmer District Works & Health engineering team for joint site inspection.',
        updatedBy: 'Dr. Vikramaditya Rathore (DM Barmer)',
        createdAt: '2026-09-25T09:00:00Z',
      },
    ],
  },
  {
    id: 'REQ-2026-0082',
    citizenId: 'usr-citizen-2',
    citizenName: 'Ananya Roy',
    citizenPhone: '+919876543211',
    title: 'Fluoride and heavy silt contamination in tube wells',
    description:
      'Community borewells in 3 contiguous gram panchayats are dispensing high-turbidity water. Over 40 children diagnosed with gastrointestinal illness.',
    originalText: 'আমাদের পঞ্চায়েতের পানীয় জলের নলকূপগুলি খারাপ হয়ে গেছে। জল ঘোলা ও পান করার অযোগ্য। শিশুরা অসুস্থ হয়ে পড়ছে।',
    translatedText:
      'The drinking water tube wells in our panchayat have gone bad. The water is turbid and unfit to drink. Children are falling ill.',
    language: 'bn',
    category: 'WATER',
    subcategory: 'Potable Drinking Water Quality',
    urgency: 'CRITICAL',
    status: 'ACTION_PLANNED',
    latitude: 23.3322,
    longitude: 86.3652,
    state: 'West Bengal',
    district: 'Purulia',
    block: 'Balarampur',
    village: 'Ghatbera',
    aiConfidence: 0.96,
    createdAt: '2026-09-21T09:20:00Z',
    updatedAt: '2026-09-24T14:00:00Z',
    similarCount: 42,
    analysis: {
      id: 'ana-2',
      requestId: 'REQ-2026-0082',
      detectedProblem: 'Groundwater fluoride contamination exceeding 2.8 mg/L and suspended sediment breakdown',
      primaryCategory: 'WATER',
      secondaryCategory: 'HEALTHCARE',
      urgencyReason: 'Active pediatric health risk and outbreak of water-borne gastrointestinal infections',
      affectedPopulationEstimate: 21500,
      duplicateGroupId: 'DUP-PURULIA-WATER-04',
      aiConfidence: 0.96,
      reasoningSummary:
        'Clustered with 42 citizen reports over 14 days. Water quality monitoring records corroborate hazardous dissolved mineral concentrations.',
      createdAt: '2026-09-21T09:21:00Z',
    },
    statusHistory: [
      {
        id: 'hist-4',
        requestId: 'REQ-2026-0082',
        status: 'SUBMITTED',
        comment: 'Submitted via citizen text input.',
        updatedBy: 'Citizen',
        createdAt: '2026-09-21T09:20:00Z',
      },
      {
        id: 'hist-5',
        requestId: 'REQ-2026-0082',
        status: 'AI_VERIFIED',
        comment: 'Classified Critical Water Quality incident. Clustered into Purulia Hotspot #2.',
        updatedBy: 'JanSetu AI Engine',
        createdAt: '2026-09-21T09:21:00Z',
      },
      {
        id: 'hist-6',
        requestId: 'REQ-2026-0082',
        status: 'ACTION_PLANNED',
        comment: 'PHED sanctioned temporary mobile RO bowser deployment and emergency pipeline link.',
        updatedBy: 'District Engineer, PHED',
        createdAt: '2026-09-24T14:00:00Z',
      },
    ],
  },
  {
    id: 'REQ-2026-0083',
    citizenId: 'usr-citizen-1',
    citizenName: 'Muthuvelan K.',
    citizenPhone: '+919876543212',
    title: 'Absence of Secondary Healthcare and 24x7 Delivery Facility',
    description:
      'Pregnant women in Jawadhu hills border must travel 48 km across ghat roads to reach a functional emergency obstetrics center.',
    originalText: 'எங்கள் மலை கிராமத்தில் பிரசவ வசதி கொண்ட அரசு ஆரம்ப சுகாதார நிலையம் இல்லை. 45 கி.மீ தொலைவு செல்ல வேண்டியுள்ளது.',
    translatedText:
      'There is no government primary health center with delivery facilities in our hill village. We have to travel 45 km.',
    language: 'ta',
    category: 'HEALTHCARE',
    subcategory: 'Maternal & Emergency Obstetric Care',
    urgency: 'HIGH',
    status: 'UNDER_REVIEW',
    latitude: 12.1211,
    longitude: 78.1582,
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    block: 'Pennagaram',
    village: 'Eriyur',
    aiConfidence: 0.93,
    createdAt: '2026-09-20T14:30:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
    similarCount: 35,
    analysis: {
      id: 'ana-3',
      requestId: 'REQ-2026-0083',
      detectedProblem: 'Severe maternal healthcare accessibility gap; transit time exceeds Golden Hour thresholds',
      primaryCategory: 'HEALTHCARE',
      secondaryCategory: 'PUBLIC_TRANSPORT',
      urgencyReason: 'Obstetric emergencies delayed by mountain terrain and absence of night medical staffing',
      affectedPopulationEstimate: 36000,
      duplicateGroupId: 'DUP-DHARMAPURI-HEALTH-01',
      aiConfidence: 0.93,
      reasoningSummary:
        'Spatial gap analysis reveals 0 functional 24/7 delivery units within a 35km radius in this tribal pocket.',
      createdAt: '2026-09-20T14:32:00Z',
    },
    statusHistory: [
      {
        id: 'hist-7',
        requestId: 'REQ-2026-0083',
        status: 'SUBMITTED',
        comment: 'Received through JanSetu Tamil speech interface.',
        updatedBy: 'JanSetu Voice Pipeline',
        createdAt: '2026-09-20T14:30:00Z',
      },
      {
        id: 'hist-8',
        requestId: 'REQ-2026-0083',
        status: 'AI_VERIFIED',
        comment: 'AI verified institutional delivery void; recommended for District Health Mission Review.',
        updatedBy: 'JanSetu AI Engine',
        createdAt: '2026-09-20T14:32:00Z',
      },
      {
        id: 'hist-9',
        requestId: 'REQ-2026-0083',
        status: 'UNDER_REVIEW',
        comment: 'Deputy Director of Health Services Dharmapuri initiated feasibility study.',
        updatedBy: 'DDHS Dharmapuri',
        createdAt: '2026-09-23T11:00:00Z',
      },
    ],
  },
  {
    id: 'REQ-2026-0084',
    citizenId: 'usr-citizen-2',
    citizenName: 'Deepak Sonowal',
    citizenPhone: '+919876543213',
    title: 'River embankment breach threatening 4 school buildings during floods',
    description:
      'Brahmaputra tributary embankment collapsed along 400m stretch. Flood waters enter two higher secondary schools every high tide.',
    originalText: 'নদীৰ মথাউৰি ভাঙি যোৱাৰ বাবে বিদ্যালয়খন পানীৰ তলত সোমাই পৰিছে। ছাত্ৰ-ছাত্ৰীসকল বিপদত পৰিছে।',
    translatedText:
      'Because the river embankment has broken, the school has gone underwater. The students are in great danger.',
    language: 'as',
    category: 'DISASTER_RESILIENCE',
    subcategory: 'Flood Embankment & School Safety',
    urgency: 'CRITICAL',
    status: 'IN_PROGRESS',
    latitude: 26.0354,
    longitude: 89.9723,
    state: 'Assam',
    district: 'Dhubri',
    block: 'Gauripur',
    village: 'Maju Char',
    aiConfidence: 0.97,
    createdAt: '2026-09-19T07:15:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
    similarCount: 51,
    analysis: {
      id: 'ana-4',
      requestId: 'REQ-2026-0084',
      detectedProblem: 'Geotechnical failure of river revetment leading to active inundation of school campus',
      primaryCategory: 'DISASTER_RESILIENCE',
      secondaryCategory: 'EDUCATION',
      urgencyReason: 'Active threat to child safety and complete shutdown of academic instruction',
      affectedPopulationEstimate: 18500,
      duplicateGroupId: 'DUP-DHUBRI-FLOOD-02',
      aiConfidence: 0.97,
      reasoningSummary:
        'Satellite radar imagery overlay confirms 1.4-meter standing water within school boundaries.',
      createdAt: '2026-09-19T07:16:00Z',
    },
    statusHistory: [
      {
        id: 'hist-10',
        requestId: 'REQ-2026-0084',
        status: 'SUBMITTED',
        comment: 'Uploaded with geotagged photo.',
        updatedBy: 'Citizen',
        createdAt: '2026-09-19T07:15:00Z',
      },
      {
        id: 'hist-11',
        requestId: 'REQ-2026-0084',
        status: 'AI_VERIFIED',
        comment: 'AI tagged Critical Disaster Alert. Auto-notified State Disaster Management Authority.',
        updatedBy: 'JanSetu Alert Engine',
        createdAt: '2026-09-19T07:16:00Z',
      },
      {
        id: 'hist-12',
        requestId: 'REQ-2026-0084',
        status: 'IN_PROGRESS',
        comment: 'Water Resources Division deployed geo-bags and heavy boulder pitching on site.',
        updatedBy: 'Executive Engineer, WRD Assam',
        createdAt: '2026-09-24T16:00:00Z',
      },
    ],
  },
  {
    id: 'REQ-2026-0085',
    citizenId: 'usr-citizen-1',
    citizenName: 'Sanjay Deshmukh',
    citizenPhone: '+919876543214',
    title: 'Frequent transformer burnouts cutting power to agricultural irrigation pumps',
    description:
      'The 100 kVA distribution transformer trips 14 times a day under overload. Standing soybean and cotton crops are wilting due to lack of borewell power.',
    originalText: 'आमच्या गावातील डीपी वारंवार जळते, त्यामुळे शेतीला पाणी देणे अशक्य झाले आहे. पिके करपून जात आहेत.',
    translatedText:
      'The DP transformer in our village burns frequently, making it impossible to water the fields. The crops are withering.',
    language: 'mr',
    category: 'ELECTRICITY',
    subcategory: 'Agricultural Feeder Stability',
    urgency: 'MEDIUM',
    status: 'ASSIGNED',
    latitude: 19.8762,
    longitude: 75.3433,
    state: 'Maharashtra',
    district: 'Aurangabad',
    block: 'Paithan',
    village: 'Bhadli',
    aiConfidence: 0.91,
    createdAt: '2026-09-18T12:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
    similarCount: 19,
    analysis: {
      id: 'ana-5',
      requestId: 'REQ-2026-0085',
      detectedProblem: 'Substation line capacity deficit causing thermal overload on 11kV agricultural feeder',
      primaryCategory: 'ELECTRICITY',
      secondaryCategory: 'AGRICULTURE',
      urgencyReason: 'Loss of farm livelihood and potential agricultural economic shock across 650 acres',
      affectedPopulationEstimate: 8200,
      duplicateGroupId: 'DUP-MAH-ELEC-07',
      aiConfidence: 0.91,
      reasoningSummary:
        'Clustered with 19 agricultural feeder requests in Paithan block. Peak load records confirm 138% overload.',
      createdAt: '2026-09-18T12:02:00Z',
    },
    statusHistory: [
      {
        id: 'hist-13',
        requestId: 'REQ-2026-0085',
        status: 'SUBMITTED',
        comment: 'Submitted via citizen portal.',
        updatedBy: 'Citizen',
        createdAt: '2026-09-18T12:00:00Z',
      },
      {
        id: 'hist-14',
        requestId: 'REQ-2026-0085',
        status: 'AI_VERIFIED',
        comment: 'AI tagged Agricultural Power crisis.',
        updatedBy: 'JanSetu AI Engine',
        createdAt: '2026-09-18T12:02:00Z',
      },
      {
        id: 'hist-15',
        requestId: 'REQ-2026-0085',
        status: 'ASSIGNED',
        comment: 'MSEDCL sub-divisional engineer tasked with transformer augmentation to 200 kVA.',
        updatedBy: 'MSEDCL Paithan',
        createdAt: '2026-09-22T10:00:00Z',
      },
    ],
  },
];

export const SEED_HOTSPOTS: Hotspot[] = [
  {
    id: 'HOT-RAJ-01',
    name: 'Chohtan-Shivnagar Rural Mobility & Health Corridor',
    location: 'Chohtan Block, Barmer, Rajasthan',
    latitude: 25.7521,
    longitude: 71.3967,
    state: 'Rajasthan',
    district: 'Barmer',
    category: 'ROAD',
    requestCount: 89,
    populationAffected: 48500,
    gapScore: 84.5,
    urgencyScore: 88.0,
    priorityScore: 86.8,
    confidence: 0.93,
    breakdown: {
      citizenDemand: 23.5, // out of 25
      populationImpact: 21.8, // out of 25
      infrastructureGap: 18.2, // out of 20
      urgency: 12.8, // out of 15
      accessibility: 10.5, // out of 15
    },
    evidenceSummary:
      '89 geotagged citizen requests corroborating 24km of sub-standard unpaved link roads. Emergency ambulance delay averages 54 minutes over state benchmark.',
    createdAt: '2026-09-20T00:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'HOT-WB-02',
    name: 'Balarampur Groundwater Fluoride Mitigation Zone',
    location: 'Balarampur Block, Purulia, West Bengal',
    latitude: 23.3322,
    longitude: 86.3652,
    state: 'West Bengal',
    district: 'Purulia',
    category: 'WATER',
    requestCount: 142,
    populationAffected: 62000,
    gapScore: 91.0,
    urgencyScore: 94.0,
    priorityScore: 92.4,
    confidence: 0.96,
    breakdown: {
      citizenDemand: 24.2,
      populationImpact: 23.0,
      infrastructureGap: 19.1,
      urgency: 14.5,
      accessibility: 11.6,
    },
    evidenceSummary:
      '142 citizen voice & text reports across 7 gram panchayats. Lab samples confirm fluoride levels up to 3.2 mg/L against 1.0 mg/L permissible limit.',
    createdAt: '2026-09-18T00:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'HOT-TN-03',
    name: 'Pennagaram Tribal Healthcare Access Arc',
    location: 'Pennagaram Block, Dharmapuri, Tamil Nadu',
    latitude: 12.1211,
    longitude: 78.1582,
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    category: 'HEALTHCARE',
    requestCount: 76,
    populationAffected: 54000,
    gapScore: 82.0,
    urgencyScore: 85.0,
    priorityScore: 83.2,
    confidence: 0.91,
    breakdown: {
      citizenDemand: 21.0,
      populationImpact: 22.4,
      infrastructureGap: 17.5,
      urgency: 12.5,
      accessibility: 9.8,
    },
    evidenceSummary:
      '76 recurring maternal emergency reports. Nearest comprehensive emergency obstetric care unit is 48 km away via ghat road.',
    createdAt: '2026-09-17T00:00:00Z',
    updatedAt: '2026-09-23T10:00:00Z',
  },
  {
    id: 'HOT-ASM-04',
    name: 'Brahmaputra Char School Flood Vulnerability Cluster',
    location: 'Gauripur Block, Dhubri, Assam',
    latitude: 26.0354,
    longitude: 89.9723,
    state: 'Assam',
    district: 'Dhubri',
    category: 'DISASTER_RESILIENCE',
    requestCount: 114,
    populationAffected: 38000,
    gapScore: 89.5,
    urgencyScore: 96.0,
    priorityScore: 90.1,
    confidence: 0.95,
    breakdown: {
      citizenDemand: 23.0,
      populationImpact: 20.5,
      infrastructureGap: 18.8,
      urgency: 14.8,
      accessibility: 13.0,
    },
    evidenceSummary:
      '114 citizen submissions documenting continuous breach of earthen dykes impacting 6 composite school clusters.',
    createdAt: '2026-09-16T00:00:00Z',
    updatedAt: '2026-09-24T15:00:00Z',
  },
  {
    id: 'HOT-MAH-05',
    name: 'Paithan Rural Agro-Power Reliability Corridor',
    location: 'Paithan Block, Aurangabad, Maharashtra',
    latitude: 19.8762,
    longitude: 75.3433,
    state: 'Maharashtra',
    district: 'Aurangabad',
    category: 'ELECTRICITY',
    requestCount: 68,
    populationAffected: 29000,
    gapScore: 74.0,
    urgencyScore: 78.0,
    priorityScore: 76.5,
    confidence: 0.89,
    breakdown: {
      citizenDemand: 19.5,
      populationImpact: 18.0,
      infrastructureGap: 15.5,
      urgency: 11.2,
      accessibility: 12.3,
    },
    evidenceSummary:
      '68 verified farmer submissions detailing unscheduled 9-hour daytime load shedding hindering lift irrigation systems.',
    createdAt: '2026-09-15T00:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
];

export const SEED_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'REC-2026-01',
    title: 'Upgradation of Chohtan-Shivnagar Link to All-Weather Bituminous Corridor',
    description:
      'Construct a 22.4 km reinforced all-weather rural arterial highway with culvert cross-drainage to restore round-the-clock emergency medical connectivity for 14 rural revenue villages.',
    category: 'ROAD',
    location: 'Chohtan Block, Barmer, Rajasthan',
    state: 'Rajasthan',
    district: 'Barmer',
    latitude: 25.7521,
    longitude: 71.3967,
    priorityScore: 86.8,
    confidence: 0.93,
    affectedPopulation: 48500,
    evidence: {
      requestCount: 89,
      existingFacilities: 'Unpaved kutcha gravel road; impassable during >20mm rainfall episodes',
      gapMetric: 'Emergency response delay of +54 minutes; nearest CHC located 34 km away',
      keyCitizenQuotations: [
        '“हमारे गांव में सड़क बहुत खराब है और बारिश के समय एम्बुलेंस नहीं आ पाती।”',
        '“स्कूल बस ने कीचड़ के कारण आना बंद कर दिया है।”',
      ],
      dataSources: [
        'JanSetu Citizen Multimodal Ingest (89 reports)',
        'Barmer District Road Asset Register 2025',
        'Survey of India Topographical Elevation Layer',
      ],
    },
    estimatedImpact:
      'Model estimates reliable year-round ambulance access for ~48,500 residents and reduction in pediatric transit mortality by an estimated 31%.',
    limitations:
      'Calculated based on available geographic elevation maps and synthetic citizen clusters. Requires on-site geotechnical soil bearing capacity verification before civil procurement.',
    status: 'APPROVED_FOR_PLANNING',
    createdAt: '2026-09-22T10:00:00Z',
    reviewedBy: 'Dr. Vikramaditya Rathore, IAS',
    reviewedAt: '2026-09-24T11:00:00Z',
  },
  {
    id: 'REC-2026-02',
    title: 'Installation of Piped Surface Water Scheme & Activated Alumina De-fluoridation Plant',
    description:
      'Deploy an automated 3.5 MLD surface water intake station and tertiary filtration module on Kangsabati tributary to replace fluoride-dense groundwater wells across 7 Gram Panchayats.',
    category: 'WATER',
    location: 'Balarampur Block, Purulia, West Bengal',
    state: 'West Bengal',
    district: 'Purulia',
    latitude: 23.3322,
    longitude: 86.3652,
    priorityScore: 92.4,
    confidence: 0.96,
    affectedPopulation: 62000,
    evidence: {
      requestCount: 142,
      existingFacilities: 'Local deep tube-wells testing positive for excessive fluoride (>2.8 mg/L)',
      gapMetric: 'Zero functional surface water treatment infrastructure currently active in target block',
      keyCitizenQuotations: [
        '“আমাদের পঞ্চায়েতের পানীয় জলের নলকূপগুলি খারাপ হয়ে গেছে। জল ঘোলা ও পান করার অযোগ্য।”',
        '“শিশুরা পেটের অসুখে ভুগছে।”',
      ],
      dataSources: [
        'JanSetu Citizen Ingest (142 reports)',
        'Central Ground Water Board (CGWB) Aquifer Report 2024',
        'State Water Quality Monitoring Cell',
      ],
    },
    estimatedImpact:
      'Model estimates potable, fluoride-compliant drinking water supply for ~62,000 residents within a 14-month phased commissioning window.',
    limitations:
      'Surface river runoff fluctuates during dry winter months; supplementary storage reservoir may be necessary.',
    status: 'PROPOSED',
    createdAt: '2026-09-21T12:00:00Z',
  },
  {
    id: 'REC-2026-03',
    title: 'Establishment of 24x7 Upgraded First Referral Unit (FRU) & Maternal Healthcare Hub',
    description:
      'Sanction a 30-bed upgraded Community Health Centre with neonatal stabilization unit and dedicated four-wheel-drive mobile medical dispensary for tribal hill settlements.',
    category: 'HEALTHCARE',
    location: 'Pennagaram Block, Dharmapuri, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    latitude: 12.1211,
    longitude: 78.1582,
    priorityScore: 83.2,
    confidence: 0.91,
    affectedPopulation: 54000,
    evidence: {
      requestCount: 76,
      existingFacilities: 'Basic sub-center staffed only 3 mornings per week; zero overnight maternity beds',
      gapMetric: 'Average travel time to nearest institutional delivery ward is 82 minutes over hilly terrain',
      keyCitizenQuotations: [
        '“எங்கள் கிராமத்தில் அவசர பிரசவ வசதி இல்லை.”',
        '“இரவு நேரத்தில் மருத்துவர்கள் இல்லாததால் உயிரிழப்பு ஏற்படுகிறது.”',
      ],
      dataSources: [
        'JanSetu Citizen Voice Ingest (76 reports)',
        'National Health Mission District Portal 2025',
        'Census Tribal Demographics 2024',
      ],
    },
    estimatedImpact:
      'Model estimates institutional delivery rate improvement from 61% to 94% across 18 tribal hamlets.',
    limitations:
      'Physician and specialist retention in hill tracts historically requires specialized incentive packages.',
    status: 'UNDER_REVIEW',
    createdAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'REC-2026-04',
    title: 'Geosynthetic Embankment Armoring & Elevated School Safety Platforms',
    description:
      'Construct a 3.8 km reinforced riprap dyke with gabion retaining walls to permanently safeguard composite education centers and village settlement from recurring inundation.',
    category: 'DISASTER_RESILIENCE',
    location: 'Gauripur Block, Dhubri, Assam',
    state: 'Assam',
    district: 'Dhubri',
    latitude: 26.0354,
    longitude: 89.9723,
    priorityScore: 90.1,
    confidence: 0.95,
    affectedPopulation: 38000,
    evidence: {
      requestCount: 114,
      existingFacilities: 'Unreinforced earthen embankment eroded during annual Brahmaputra surge',
      gapMetric: 'Schools flooded an average of 42 instructional days per monsoon season',
      keyCitizenQuotations: [
        '“মথাউৰি ভাঙি যোৱাৰ বাবে বিদ্যালয়খন পানীৰ তলত।”',
        '“ছাত্ৰ-ছাত্ৰীসকলে নাও লৈহে যাব লগা হয়।”',
      ],
      dataSources: [
        'JanSetu Photo & Voice Ingest (114 reports)',
        'Assam State Disaster Management Authority flood hazard maps',
        'ISRO Bhuvan Spatial Flood Inundation Archive',
      ],
    },
    estimatedImpact:
      'Model estimates protection of 6 school campuses and 3,400 students with uninterrupted academic calendar continuity.',
    limitations:
      'Heavy siltation patterns require periodic dredging; hydraulic modeling must precede final structural cross-sections.',
    status: 'PROPOSED',
    createdAt: '2026-09-19T14:00:00Z',
  },
];

export const SEED_INFRASTRUCTURE: InfrastructureAsset[] = [
  {
    id: 'INF-001',
    name: 'Chohtan Community Health Centre',
    type: 'CLINIC',
    latitude: 25.6892,
    longitude: 71.3211,
    state: 'Rajasthan',
    district: 'Barmer',
    block: 'Chohtan',
    capacity: '12 Beds, 1 Medical Officer',
    status: 'OPERATIONAL',
    source: 'State Health Directorate',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'INF-002',
    name: 'Barmer District Hospital',
    type: 'HOSPITAL',
    latitude: 25.7521,
    longitude: 71.3967,
    state: 'Rajasthan',
    district: 'Barmer',
    block: 'Barmer',
    capacity: '300 Beds, Intensive Care, Neonatal Unit',
    status: 'OPERATIONAL',
    source: 'National Health Portal',
    createdAt: '2023-05-15T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'INF-003',
    name: 'Balarampur Rural Hospital',
    type: 'HOSPITAL',
    latitude: 23.0982,
    longitude: 86.2234,
    state: 'West Bengal',
    district: 'Purulia',
    block: 'Balarampur',
    capacity: '30 Beds',
    status: 'OPERATIONAL',
    source: 'West Bengal Health Dept',
    createdAt: '2023-08-20T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'INF-004',
    name: 'Pennagaram Taluk Hospital',
    type: 'HOSPITAL',
    latitude: 12.1345,
    longitude: 77.8923,
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    block: 'Pennagaram',
    capacity: '50 Beds',
    status: 'OPERATIONAL',
    source: 'TN Health Systems Project',
    createdAt: '2024-02-14T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'INF-005',
    name: 'Gauripur Model Higher Secondary School',
    type: 'SCHOOL',
    latitude: 26.0821,
    longitude: 89.9723,
    state: 'Assam',
    district: 'Dhubri',
    block: 'Gauripur',
    capacity: '850 Students',
    status: 'OPERATIONAL',
    source: 'Samagra Shiksha Assam',
    createdAt: '2022-09-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'INF-006',
    name: 'Paithan 132/33kV MSETCL Grid Substation',
    type: 'ELECTRICITY_FACILITY',
    latitude: 19.4789,
    longitude: 75.3892,
    state: 'Maharashtra',
    district: 'Aurangabad',
    block: 'Paithan',
    capacity: '50 MVA',
    status: 'OPERATIONAL',
    source: 'Maharashtra State Electricity Transmission Co.',
    createdAt: '2021-04-10T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'PRJ-2026-001',
    recommendationId: 'REC-2026-01',
    name: 'Barmer Rural Arterial Upgrade (Chohtan - Shivnagar Stretch)',
    description: 'Civil construction of 22.4 km all-weather corridor under State Rural Works Scheme.',
    location: 'Chohtan, Barmer, Rajasthan',
    category: 'ROAD',
    budget: 18.5, // 18.5 Crores INR
    status: 'TENDER_PUBLISHED',
    createdAt: '2026-09-24T12:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'PRJ-2026-002',
    recommendationId: 'REC-2026-02',
    name: 'Purulia Safe Drinking Water Mission - Phase IV',
    description: '3.5 MLD surface water intake and automated filtration plant construction.',
    location: 'Balarampur, Purulia, West Bengal',
    category: 'WATER',
    budget: 34.2, // 34.2 Crores INR
    status: 'DPR_PREPARATION',
    createdAt: '2026-09-22T09:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
  },
];

export const SEED_DATA_SOURCES: DataSourceItem[] = [
  {
    id: 'DS-01',
    name: 'JanSetu Citizen Voice & Multimodal Ingest Pipeline',
    provider: 'JanSetu AI Platform',
    date: 'Continuous Real-time',
    coverage: 'National (12 States Active)',
    description:
      'Citizen submitted text, speech-to-text, photos, and geotagged requests processed via Gemini multimodal analysis.',
    lastUpdated: '2026-09-26T22:00:00Z',
    license: 'Digital Public Good (DPG Open Public Schema)',
    status: 'ACTIVE',
    recordCount: 4892,
  },
  {
    id: 'DS-02',
    name: 'Census & Local Government Directory (LGD) Geospatial Demographics',
    provider: 'Ministry of Panchayati Raj / Census Directorate (Synthetic Demo Mirror)',
    date: '2024 Archive',
    coverage: '768 Districts, 6,612 Blocks',
    description:
      'Gram Panchayat population counts, household density, and geographic bounding extents used for impact normalization.',
    lastUpdated: '2026-07-15T00:00:00Z',
    license: 'Government Open Data License - India (Synthetic Mirror)',
    status: 'SYNTHETIC_DEMO',
    recordCount: 18450,
  },
  {
    id: 'DS-03',
    name: 'PMGSY / State Rural Works Road Asset Geodatabase',
    provider: 'National Rural Infrastructure Development Agency (Demo Mirror)',
    date: '2025 Upgraded',
    coverage: 'Rural Road Networks',
    description:
      'Surface quality grading (Bituminous, Gravel, Track), bridge crossings, and maintenance history records.',
    lastUpdated: '2026-08-10T00:00:00Z',
    license: 'Open Access Research License',
    status: 'SYNTHETIC_DEMO',
    recordCount: 6240,
  },
  {
    id: 'DS-04',
    name: 'National Health Portal & Ayushman Bharat Facility Register',
    provider: 'National Health Authority (Synthetic Demo Mirror)',
    date: '2025 Periodic Audit',
    coverage: 'Primary, Secondary, Tertiary Healthcare Points',
    description:
      'Bed capacities, specialist rosters, distance-to-emergency calculations, and neonatal care capabilities.',
    lastUpdated: '2026-08-30T00:00:00Z',
    license: 'CC-BY 4.0 Public Domain Mirror',
    status: 'SYNTHETIC_DEMO',
    recordCount: 14120,
  },
  {
    id: 'DS-05',
    name: 'Central Ground Water Board (CGWB) Aquifer Quality Layer',
    provider: 'Ministry of Jal Shakti (Demo Mirror)',
    date: '2024 Pre-Monsoon Survey',
    coverage: 'Hydrogeological Blocks',
    description:
      'Water quality parameters including Fluoride, Arsenic, Salinity, and Nitrate concentration matrices.',
    lastUpdated: '2026-06-18T00:00:00Z',
    license: 'Open Government Data',
    status: 'SYNTHETIC_DEMO',
    recordCount: 3820,
  },
];
